name: Scala CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Run tests
      run: sbt assembly
    - name: push
      uses: github-actions-x/commit@v2.5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'publish'
        force-add: 'true'
        files: "*"
        name: commiter name
        email: my.github@email.com 
